# Site settings
title: Ranjan Jayapal
email: ranjan.jayapal.us@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Computer Freak
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ranjanjayapal.github.io" # the base hostname & protocol for your site
twitter_username: RJ7_logan
github_username:  ranjanjayapal

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
